---
title: "Project_2_JuliaMartin"
output: html_document
date: "2024-09-24"
---

### Call necessary packages

```{r}
library(tidyverse)
library(tidytuesdayR)
library(usethis)
library(here)
library(lubridate)
```

## Part 1

### Part 1A: Exponential transformation

```{r}
Exp <- function(x, k) {
    series <- rep(NA,k+1)
    for(i in 0:k) {
      series[i+1] <- (x^i) / factorial(i)
    }
    sum(series)
}
```

### Part 1B: Sample mean and sample standard deviation

```{r}
sample_mean <- function(x) {
    sum(x) / length(x)
}

sample_sd <- function(x) {
    xbar <- sum(x) / length(x)
    sqrt(sum((x - xbar)^2) / (length(x)-1))
}
```

### Part 1C: Confidence intervals 

```{r}
calculate_CI <- function(x, conf = 0.95) {
  N <- length(x)
  alpha <- 1 - conf
  degrees_freedom <- N - 1
  t_score <- qt(p = alpha / 2, df = degrees_freedom, lower.tail = FALSE)
  xbar <- sample_mean(x)
  s_xbar <- sample_sd(x) / sqrt(N)
  CI <- c(xbar-(t_score*s_xbar), xbar+(t_score*s_xbar))
  CI
}

# test the function with the confint() function with two different confidence levels:

# vector x
x <- c(5,7,1,2,5,0,8,7,6,5,3,3,4)
dat <- data.frame(x = x)
fit <- lm(x ~ 1, dat)

# Calculate a 95% confidence interval
confint(fit, level = 0.95)
calculate_CI(x, 0.95)

# Calculate a 90% confidence interval
confint(fit, level = 0.9)
calculate_CI(x, 0.9)

# For both a confidence level of 90% and 95%, my function matches the output of the confint function
```

## Part 2 

Load data  

```{r}
rainfall <- readRDS(here("data", "tuesdata_rainfall.RDS"))
temperature <- readRDS(here("data", "tuesdata_temperature.RDS"))
glimpse(rainfall)
glimpse(temperature)
```

Tasks  

```{r}
df <- rainfall %>% 
  drop_na() %>% 
  mutate(date=ymd(paste(year, month, day, sep = "-"))) %>% 
  select (-c(month,day)) %>% 
  mutate(city_name=str_to_upper(city_name))

df <- inner_join(df, temperature, by = c("city_name"="city_name", "date"="date"), relationship = "many-to-many")
dim(df)
head(df,10)
```
## Part 3  

### Part 3A: Plotting Temperature Data Over Time

```{r}
temp_plot <- df %>% 
  filter(year >= 2014)

ggplot(temp_plot, aes(date, temperature, group = temp_type, color = temp_type)) +
  geom_line() +
  facet_wrap(~city_name) + 
  guides(color = guide_legend(title = "Temperature Type")) + scale_color_manual(labels = c("Maximum", "Minimum"), values = c("red1","blue4")) + ggtitle("Maximum and Minimum Temperatures in 5 Australian Cites from 2014-2019") + ylab("Temperature (degrees Celcius)") + xlab("Date") + labs(subtitle = str_wrap("Minimum temperatures have remained roughly stable, but Sydney is seeing a slight rise in maximum temperatures during the Summer months and Melbourne and Perth are seeing a slight decrease in maximum temperatures during the Summer")) + theme(legend.position = "bottom", title = element_text(family = "Optima"))
```




